export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// PARISH ACTIONS TYPES
export const GET_PARISHES = "GET_PARISHES";
export const VIEW_PARISH = "VIEW_PARISH";
export const CREATE_PARISH = "CREATE_PARISH";
export const DELETE_PARISH = "DELETE_PARISH";

// PARISH ACTIONS TYPES
export const GET_SHEPHERDS = "GET_SHEPHERDS";
export const VIEW_SHEPHERD = "VIEW_SHEPHERD";
export const CREATE_SHEPHERD = "CREATE_SHEPHERD";
export const DELETE_SHEPHERD = "DELETE_SHEPHERD";
